name: Azure PowerShell Automation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Az Module
        shell: pwsh
        run: |
          Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber
          Import-Module Az

      - name: Login to Azure
        shell: pwsh
        run: |
          $creds = '${{ secrets.AZURE_CREDENTIALS }}' | ConvertFrom-Json
          $securePassword = ConvertTo-SecureString $creds.clientSecret -AsPlainText -Force
          $psCred = New-Object System.Management.Automation.PSCredential ($creds.clientId, $securePassword)
          Connect-AzAccount -ServicePrincipal -Credential $psCred -TenantId $creds.tenantId

      - name: Run PowerShell Script
        shell: pwsh
        env:
          VM_USERNAME: ${{ secrets.VM_USERNAME }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
        run: ./create-vm.ps1


